from typing import TypedDict

class ArtEntry(TypedDict):
	name: str
	size: int

def decrypt(encrypted: bytes, /) -> bytes: ...
def encrypt(plaintext: bytes, /) -> bytes: ...
def loads(encrypted: bytes, /) -> list[ArtEntry]: ...
def zip_archive(entries: dict[str, bytes], /) -> bytes: ...
